### PR TITLE
add end db session

### PR DESCRIPTION
**Pull request by lotterfriends**
End client session after creation, so following script don't get any ShareRowExclusiveLock exceptions

### CODE REVIEW

**Comment by adriaandotcom** [comment]
@lotterfriends, thanks for this PR. It's a while ago, but would you mind merging master into this branch? And how can we add a test for the ShareRowExclusiveLock? Do you have any ideas for that?

**Comment by lotterfriends** [comment]
@adriaanvanrossum  I will check :)

**Comment by adriaandotcom** [comment]
Let me know if you need help!

**Comment by lotterfriends** [comment]
I don't know how to cover the additional lines in simple way, without changing how the index.js work or how the tests are implemented

**Comment by adriaandotcom** [comment]
What would you suggest to change to the index.js file and the tests? Open for suggestions if it improves the quality.

**Comment by audiBookning** [comment]
@lotterfriends  Your PR is really a needed addition.
I have a suggestion for the test problem.
As suggested in this issue [Application name for connection](https://github.com/brianc/node-postgres/issues/1223), one can pass an "application_name" to the connection config.
One can also make a query to get the database connections stats as suggested in this Stack post [How to list active connections on PostgreSQL?](https://stackoverflow.com/questions/27435839/how-to-list-active-connections-on-postgresql).
So the solution would pass by adding `application_name: 'pgtools'` in the config.
Then the test sequence would be something like this:

- first check that that pgtools wasn't in the list of application_names
- execute some pgtools method
- check that that pgtools still wasn't in the list of application_names

The query to check could be something like:
```SQL
SELECT 
    ,application_name
FROM pg_stat_activity;
```
What do you think?

**Comment by olalonde** [comment]
We had a big refactor of the code and I believe this issue was fixed but it would be nice to add some tests for it.

**Pull request closed without merging**
