### PR TITLE
optimize the callback when exist an error

### PR DESCRIPTION
**Pull request by dotenorio**

### CODE REVIEW

**Comment by dotenorio** [comment]
Please see it!

**Comment by olalonde** [comment]
Thanks! Can you just make the tests pass? There seems to be a build error with travis.

**Comment by bcoe** [comment]
@dotenorio mind rebasing and fixing up the Travis tests; would happily still land this.

**Comment by bcoe** [comment]
@dotenorio I'm running around GitHub cleaning up stale issues; please re-open this if you have time to put some work into it again.

**Pull request closed without merging**
